#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-cayman
title: Mini-workshop on Higgs bundles
# description: Hodge theory and vanishing theorem
# theme: jekyll-theme-cayman